// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: heL2P6rJiLNgtnBJPb6i1m
// Component: 75pOOjr2QFNp

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { ProductMedia } from "@plasmicpkgs/commerce";
import { ProductLink } from "@plasmicpkgs/commerce";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_jbs_storefront.module.css"; // plasmic-import: heL2P6rJiLNgtnBJPb6i1m/projectcss
import sty from "./PlasmicTestproduct.module.css"; // plasmic-import: 75pOOjr2QFNp/css

createPlasmicElementProxy;

export type PlasmicTestproduct__VariantMembers = {};
export type PlasmicTestproduct__VariantsArgs = {};
type VariantPropType = keyof PlasmicTestproduct__VariantsArgs;
export const PlasmicTestproduct__VariantProps = new Array<VariantPropType>();

export type PlasmicTestproduct__ArgsType = {};
type ArgPropType = keyof PlasmicTestproduct__ArgsType;
export const PlasmicTestproduct__ArgProps = new Array<ArgPropType>();

export type PlasmicTestproduct__OverridesType = {
  root?: Flex__<"div">;
  productMedia?: Flex__<typeof ProductMedia>;
  productLink?: Flex__<typeof ProductLink>;
};

export interface DefaultTestproductProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTestproduct__RenderFunc(props: {
  variants: PlasmicTestproduct__VariantsArgs;
  args: PlasmicTestproduct__ArgsType;
  overrides: PlasmicTestproduct__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <ProductMedia
        data-plasmic-name={"productMedia"}
        data-plasmic-override={overrides.productMedia}
        className={classNames("__wab_instance", sty.productMedia)}
      />

      <ProductLink
        data-plasmic-name={"productLink"}
        data-plasmic-override={overrides.productLink}
        className={classNames("__wab_instance", sty.productLink)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "productMedia", "productLink"],
  productMedia: ["productMedia"],
  productLink: ["productLink"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  productMedia: typeof ProductMedia;
  productLink: typeof ProductLink;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTestproduct__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTestproduct__VariantsArgs;
    args?: PlasmicTestproduct__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTestproduct__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTestproduct__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTestproduct__ArgProps,
          internalVariantPropNames: PlasmicTestproduct__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTestproduct__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestproduct";
  } else {
    func.displayName = `PlasmicTestproduct.${nodeName}`;
  }
  return func;
}

export const PlasmicTestproduct = Object.assign(
  // Top-level PlasmicTestproduct renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    productMedia: makeNodeComponent("productMedia"),
    productLink: makeNodeComponent("productLink"),

    // Metadata about props expected for PlasmicTestproduct
    internalVariantProps: PlasmicTestproduct__VariantProps,
    internalArgProps: PlasmicTestproduct__ArgProps
  }
);

export default PlasmicTestproduct;
/* prettier-ignore-end */
