// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: heL2P6rJiLNgtnBJPb6i1m
// Component: sFlg1tQbot

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import FullPage from "../../FullPage"; // plasmic-import: VpRM2nIn0R/component
import { ProductBox } from "@plasmicpkgs/commerce"; // plasmic-import: 1gYJf_XBZUAD/codeComponent
import { PlasmicHead } from "@plasmicapp/react-web"; // plasmic-import: Y-3ZgxdS1wv60n/codeComponent
import { ProductMedia } from "@plasmicpkgs/commerce"; // plasmic-import: qpULM0wwWW/codeComponent
import { ProductTextField } from "@plasmicpkgs/commerce"; // plasmic-import: S1F4q0wN6b/codeComponent
import { ProductPriceComponent } from "@plasmicpkgs/commerce"; // plasmic-import: _PaJxGc8gf/codeComponent
import { ProductVariantPicker } from "@plasmicpkgs/commerce"; // plasmic-import: i3vHZr7erKX/codeComponent
import AddToCartCustomButton from "../../AddToCartCustomButton"; // plasmic-import: AyNa8RYOflZ1/component
import { AntdAccordion } from "@plasmicpkgs/antd5/skinny/registerCollapse"; // plasmic-import: oPUhN99n4VXI/codeComponent
import { accordionHelpers as AntdAccordion_Helpers } from "@plasmicpkgs/antd5/skinny/registerCollapse"; // plasmic-import: oPUhN99n4VXI/codeComponentHelper
import { AntdAccordionItem } from "@plasmicpkgs/antd5/skinny/registerCollapse"; // plasmic-import: 4mmDdnlyWx2k/codeComponent
import { GraphqlFetcher } from "@plasmicpkgs/plasmic-query"; // plasmic-import: 0DrxdjD45dkx/codeComponent
import Section from "../../Section"; // plasmic-import: GMAR4VOl00/component
import ProductCardJbs from "../../ProductCardJbs"; // plasmic-import: Ft4Mem_Zab/component
import Button2 from "../../Button2"; // plasmic-import: yEsI5slGwPm/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources"; // plasmic-import: 1xopR4ZBZs2K4b/codeComponent

import { useScreenVariants as useScreenVariants_6Hzia3M7Np4Ulu } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 6hzia3m7Np4ulu/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_jbs_storefront.module.css"; // plasmic-import: heL2P6rJiLNgtnBJPb6i1m/projectcss
import sty from "./PlasmicProductPage.module.css"; // plasmic-import: sFlg1tQbot/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: ew07hyuAC0c/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: 3r4KXWygi9v/icon

createPlasmicElementProxy;

export type PlasmicProductPage__VariantMembers = {};
export type PlasmicProductPage__VariantsArgs = {};
type VariantPropType = keyof PlasmicProductPage__VariantsArgs;
export const PlasmicProductPage__VariantProps = new Array<VariantPropType>();

export type PlasmicProductPage__ArgsType = {};
type ArgPropType = keyof PlasmicProductPage__ArgsType;
export const PlasmicProductPage__ArgProps = new Array<ArgPropType>();

export type PlasmicProductPage__OverridesType = {
  root?: p.Flex<"div">;
  fullPage?: p.Flex<typeof FullPage>;
  columns?: p.Flex<"div">;
  pageMetadataOverride?: p.Flex<typeof PlasmicHead>;
  productMedia?: p.Flex<typeof ProductMedia>;
  productPrice?: p.Flex<typeof ProductPriceComponent>;
  productVariantPicker?: p.Flex<typeof ProductVariantPicker>;
  addToCartCustomButton?: p.Flex<typeof AddToCartCustomButton>;
  accordion?: p.Flex<typeof AntdAccordion>;
  section?: p.Flex<typeof Section>;
  productCardJbs?: p.Flex<typeof ProductCardJbs>;
  button2?: p.Flex<typeof Button2>;
  svg?: p.Flex<"svg">;
};

export interface DefaultProductPageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProductPage__RenderFunc(props: {
  variants: PlasmicProductPage__VariantsArgs;
  args: PlasmicProductPage__ArgsType;
  overrides: PlasmicProductPage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof p.useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "accordion.activePanelId",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: p.generateOnMutateForSpec(
          "activePanelId",
          AntdAccordion_Helpers
        )
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_6Hzia3M7Np4Ulu()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <FullPage
            data-plasmic-name={"fullPage"}
            data-plasmic-override={overrides.fullPage}
            className={classNames("__wab_instance", sty.fullPage)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column___88Slm)}>
                <ProductBox
                  className={classNames(
                    "__wab_instance",
                    sty.productBox__k8N2T
                  )}
                  id={(() => {
                    try {
                      return $ctx.params.slug;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                >
                  <ph.DataCtxReader>
                    {$ctx => (
                      <React.Fragment>
                        <PlasmicHead
                          data-plasmic-name={"pageMetadataOverride"}
                          data-plasmic-override={overrides.pageMetadataOverride}
                          className={classNames(
                            "__wab_instance",
                            sty.pageMetadataOverride
                          )}
                          description={(() => {
                            try {
                              return undefined;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          image={(() => {
                            try {
                              return $ctx.currentProduct.images[0].url;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                          title={(() => {
                            try {
                              return $ctx.currentProduct.name;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hnKz
                          )}
                        >
                          {(_par =>
                            !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                            (() => {
                              try {
                                return $ctx.currentProduct.images;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return [];
                                }
                                throw e;
                              }
                            })()
                          ).map((__plasmic_item_0, __plasmic_idx_0) => {
                            const currentItem = __plasmic_item_0;
                            const currentIndex = __plasmic_idx_0;
                            return (
                              <ProductMedia
                                data-plasmic-name={"productMedia"}
                                data-plasmic-override={overrides.productMedia}
                                className={classNames(
                                  "__wab_instance",
                                  sty.productMedia
                                )}
                                key={currentIndex}
                                mediaIndex={(() => {
                                  try {
                                    return currentIndex;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return undefined;
                                    }
                                    throw e;
                                  }
                                })()}
                              />
                            );
                          })}
                        </div>
                      </React.Fragment>
                    )}
                  </ph.DataCtxReader>
                </ProductBox>
              </div>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__vIqh5)}
              >
                <ProductBox
                  className={classNames(
                    "__wab_instance",
                    sty.productBox__hfBk0
                  )}
                  id={(() => {
                    try {
                      return $ctx.params.slug;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                >
                  <ph.DataCtxReader>
                    {$ctx => (
                      <React.Fragment>
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__emiHk
                          )}
                        >
                          <ProductTextField
                            className={classNames(
                              "__wab_instance",
                              sty.productTextField__kxHmd
                            )}
                            field={"name"}
                          />

                          <ProductPriceComponent
                            data-plasmic-name={"productPrice"}
                            data-plasmic-override={overrides.productPrice}
                            className={classNames(
                              "__wab_instance",
                              sty.productPrice
                            )}
                          />

                          {(() => {
                            try {
                              return $ctx.currentProduct.variants.length > 1;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return true;
                              }
                              throw e;
                            }
                          })() ? (
                            <ProductVariantPicker
                              data-plasmic-name={"productVariantPicker"}
                              data-plasmic-override={
                                overrides.productVariantPicker
                              }
                              className={classNames(
                                "__wab_instance",
                                sty.productVariantPicker
                              )}
                            />
                          ) : null}
                          <ProductTextField
                            className={classNames(
                              "__wab_instance",
                              sty.productTextField__bQZeN
                            )}
                            field={"description"}
                          />
                        </p.Stack>
                        <AddToCartCustomButton
                          data-plasmic-name={"addToCartCustomButton"}
                          data-plasmic-override={
                            overrides.addToCartCustomButton
                          }
                          className={classNames(
                            "__wab_instance",
                            sty.addToCartCustomButton
                          )}
                        />

                        {(() => {
                          const child$Props = {
                            activeKey: p.generateStateValueProp($state, [
                              "accordion",
                              "activePanelId"
                            ]),
                            bordered: false,
                            className: classNames(
                              "__wab_instance",
                              sty.accordion
                            ),
                            expandIconPosition: "end",
                            items: (
                              <React.Fragment>
                                <AntdAccordionItem
                                  className={classNames(
                                    "__wab_instance",
                                    sty.accordionItem__cyA7Q
                                  )}
                                  headerClass={classNames({
                                    [sty["pcls_glhVZ5pr61R9"]]: true
                                  })}
                                  id={1}
                                  label2={
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text___6OyBx
                                      )}
                                    >
                                      {"Product Details"}
                                    </div>
                                  }
                                  showArrow={true}
                                >
                                  <GraphqlFetcher
                                    className={classNames(
                                      "__wab_instance",
                                      sty.graphQlFetcher__v5IcA
                                    )}
                                    dataName={"fetchedData"}
                                    errorDisplay={
                                      <ph.DataCtxReader>
                                        {$ctx => "Error fetching data"}
                                      </ph.DataCtxReader>
                                    }
                                    headers={{
                                      "Content-Type": "application/json",
                                      Accept: "application/json",
                                      "X-Shopify-Storefront-Access-Token":
                                        "0f43cbfd628ae6e4fef6a34969378290"
                                    }}
                                    loadingDisplay={
                                      <ph.DataCtxReader>
                                        {$ctx => "Loading..."}
                                      </ph.DataCtxReader>
                                    }
                                    method={"POST"}
                                    noLayout={false}
                                    query={{
                                      query:
                                        'query MyQuery($id: ID!) {\n  product(id: $id) {\n    metafield(key: "product_details", namespace: "descriptors") {\n      value\n    }\n}\n}',
                                      variables: { name: "Rick Sanchez" }
                                    }}
                                    url={
                                      "https://juhubeachstudio.myshopify.com/api/2023-07/graphql.json"
                                    }
                                    varOverrides={(() => {
                                      try {
                                        return { id: $ctx.currentProduct.id };
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return {};
                                        }
                                        throw e;
                                      }
                                    })()}
                                  >
                                    <ph.DataCtxReader>
                                      {$ctx => (
                                        <div
                                          className={classNames(
                                            projectcss.all,
                                            projectcss.__wab_text,
                                            sty.text__yaIk
                                          )}
                                        >
                                          <React.Fragment>
                                            {(() => {
                                              try {
                                                return $ctx.fetchedData.data
                                                  .product.metafield.value;
                                              } catch (e) {
                                                if (
                                                  e instanceof TypeError ||
                                                  e?.plasmicType ===
                                                    "PlasmicUndefinedDataError"
                                                ) {
                                                  return "";
                                                }
                                                throw e;
                                              }
                                            })()}
                                          </React.Fragment>
                                        </div>
                                      )}
                                    </ph.DataCtxReader>
                                  </GraphqlFetcher>
                                </AntdAccordionItem>
                                <AntdAccordionItem
                                  className={classNames(
                                    "__wab_instance",
                                    sty.accordionItem__jPeb
                                  )}
                                  headerClass={classNames({
                                    [sty["pcls_LhikHYKCERFN"]]: true
                                  })}
                                  id={1}
                                  label2={
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__chhbz
                                      )}
                                    >
                                      {"Wash+Care Instructions"}
                                    </div>
                                  }
                                  showArrow={true}
                                >
                                  <GraphqlFetcher
                                    className={classNames(
                                      "__wab_instance",
                                      sty.graphQlFetcher__yFr
                                    )}
                                    dataName={"fetchedData"}
                                    errorDisplay={
                                      <ph.DataCtxReader>
                                        {$ctx => "Error fetching data"}
                                      </ph.DataCtxReader>
                                    }
                                    headers={{
                                      "Content-Type": "application/json",
                                      Accept: "application/json",
                                      "X-Shopify-Storefront-Access-Token":
                                        "0f43cbfd628ae6e4fef6a34969378290"
                                    }}
                                    loadingDisplay={
                                      <ph.DataCtxReader>
                                        {$ctx => "Loading..."}
                                      </ph.DataCtxReader>
                                    }
                                    method={"POST"}
                                    noLayout={false}
                                    query={{
                                      query:
                                        'query MyQuery($id: ID!) {\n  product(id: $id) {\n    metafield(key: "care_guide", namespace: "descriptors") {\n      value\n    }\n}\n}',
                                      variables: { name: "Rick Sanchez" }
                                    }}
                                    url={
                                      "https://juhubeachstudio.myshopify.com/api/2023-07/graphql.json"
                                    }
                                    varOverrides={(() => {
                                      try {
                                        return { id: $ctx.currentProduct.id };
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return {};
                                        }
                                        throw e;
                                      }
                                    })()}
                                  >
                                    <ph.DataCtxReader>
                                      {$ctx => (
                                        <div
                                          className={classNames(
                                            projectcss.all,
                                            projectcss.__wab_text,
                                            sty.text__qvO4P
                                          )}
                                        >
                                          <React.Fragment>
                                            {(() => {
                                              try {
                                                return $ctx.fetchedData.data
                                                  .product.metafield.value;
                                              } catch (e) {
                                                if (
                                                  e instanceof TypeError ||
                                                  e?.plasmicType ===
                                                    "PlasmicUndefinedDataError"
                                                ) {
                                                  return "";
                                                }
                                                throw e;
                                              }
                                            })()}
                                          </React.Fragment>
                                        </div>
                                      )}
                                    </ph.DataCtxReader>
                                  </GraphqlFetcher>
                                </AntdAccordionItem>
                                <AntdAccordionItem
                                  className={classNames(
                                    "__wab_instance",
                                    sty.accordionItem__sMj4I
                                  )}
                                  headerClass={classNames({
                                    [sty["pcls_rc70p24kHQ1o"]]: true
                                  })}
                                  id={1}
                                  label2={
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__dNtKk
                                      )}
                                    >
                                      {"Materials"}
                                    </div>
                                  }
                                  showArrow={true}
                                >
                                  <GraphqlFetcher
                                    className={classNames(
                                      "__wab_instance",
                                      sty.graphQlFetcher__rVikm
                                    )}
                                    dataName={"fetchedData"}
                                    errorDisplay={
                                      <ph.DataCtxReader>
                                        {$ctx => "Error fetching data"}
                                      </ph.DataCtxReader>
                                    }
                                    headers={{
                                      "Content-Type": "application/json",
                                      Accept: "application/json",
                                      "X-Shopify-Storefront-Access-Token":
                                        "0f43cbfd628ae6e4fef6a34969378290"
                                    }}
                                    loadingDisplay={
                                      <ph.DataCtxReader>
                                        {$ctx => "Loading..."}
                                      </ph.DataCtxReader>
                                    }
                                    method={"POST"}
                                    noLayout={false}
                                    query={{
                                      query:
                                        'query MyQuery($id: ID!) {\n  product(id: $id) {\n    metafield(key: "materials", namespace: "descriptors") {\n      value\n    }\n}\n}',
                                      variables: { name: "Rick Sanchez" }
                                    }}
                                    url={
                                      "https://juhubeachstudio.myshopify.com/api/2023-07/graphql.json"
                                    }
                                    varOverrides={(() => {
                                      try {
                                        return { id: $ctx.currentProduct.id };
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return {};
                                        }
                                        throw e;
                                      }
                                    })()}
                                  >
                                    <ph.DataCtxReader>
                                      {$ctx => (
                                        <div
                                          className={classNames(
                                            projectcss.all,
                                            projectcss.__wab_text,
                                            sty.text__ptSi9
                                          )}
                                        >
                                          <React.Fragment>
                                            {(() => {
                                              try {
                                                return $ctx.fetchedData.data
                                                  .product.metafield.value;
                                              } catch (e) {
                                                if (
                                                  e instanceof TypeError ||
                                                  e?.plasmicType ===
                                                    "PlasmicUndefinedDataError"
                                                ) {
                                                  return "";
                                                }
                                                throw e;
                                              }
                                            })()}
                                          </React.Fragment>
                                        </div>
                                      )}
                                    </ph.DataCtxReader>
                                  </GraphqlFetcher>
                                </AntdAccordionItem>
                              </React.Fragment>
                            ),

                            onChange:
                              p.generateStateOnChangePropForCodeComponents(
                                $state,
                                "activePanelId",
                                ["accordion", "activePanelId"],
                                AntdAccordion_Helpers
                              ),
                            size: "large"
                          };
                          p.initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "activePanelId",
                                plasmicStateName: "accordion.activePanelId"
                              }
                            ],

                            [],
                            AntdAccordion_Helpers ?? {},
                            child$Props
                          );

                          return (
                            <AntdAccordion
                              data-plasmic-name={"accordion"}
                              data-plasmic-override={overrides.accordion}
                              {...child$Props}
                            />
                          );
                        })()}
                      </React.Fragment>
                    )}
                  </ph.DataCtxReader>
                </ProductBox>
              </p.Stack>
            </p.Stack>
            <Section
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              className={classNames("__wab_instance", sty.section)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__uIStc)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ckdj2
                  )}
                >
                  {"Look how cute -"}
                </div>
              </div>
              <ProductBox
                className={classNames("__wab_instance", sty.productBox__sXbvh)}
                id={(() => {
                  try {
                    return $ctx.params.slug;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
              >
                <ph.DataCtxReader>
                  {$ctx => (
                    <GraphqlFetcher
                      className={classNames(
                        "__wab_instance",
                        sty.graphQlFetcher__pCFol
                      )}
                      dataName={"fetchedData"}
                      errorDisplay={
                        <ph.DataCtxReader>
                          {$ctx => "Error fetching data"}
                        </ph.DataCtxReader>
                      }
                      headers={{
                        "Content-Type": "application/json",
                        Accept: "application/json",
                        "X-Shopify-Storefront-Access-Token":
                          "0f43cbfd628ae6e4fef6a34969378290"
                      }}
                      loadingDisplay={
                        <ph.DataCtxReader>
                          {$ctx => "Loading..."}
                        </ph.DataCtxReader>
                      }
                      method={"POST"}
                      noLayout={false}
                      query={{
                        query:
                          'query MyQuery($id: ID!) {\n  product(id: $id) {\n    metafield(key: "related_products", namespace: "shopify--discovery--product_recommendation") {\n      value\n    }\n}\n}',
                        variables: { name: "Rick Sanchez" }
                      }}
                      url={
                        "https://juhubeachstudio.myshopify.com/api/2023-07/graphql.json"
                      }
                      varOverrides={(() => {
                        try {
                          return { id: $ctx.currentProduct.id };
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return {};
                          }
                          throw e;
                        }
                      })()}
                    >
                      <ph.DataCtxReader>
                        {$ctx => (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__uE3Fy
                            )}
                          >
                            {(_par =>
                              !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                              (() => {
                                try {
                                  return JSON.parse(
                                    $ctx.fetchedData.data.product.metafield
                                      .value
                                  );
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return [];
                                  }
                                  throw e;
                                }
                              })()
                            ).map((__plasmic_item_0, __plasmic_idx_0) => {
                              const currentItem = __plasmic_item_0;
                              const currentIndex = __plasmic_idx_0;
                              return (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__mcOpP
                                  )}
                                  key={currentIndex}
                                >
                                  <ProductBox
                                    className={classNames(
                                      "__wab_instance",
                                      sty.productBox__k8Qx4
                                    )}
                                    id={(() => {
                                      try {
                                        return currentItem;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return undefined;
                                        }
                                        throw e;
                                      }
                                    })()}
                                  >
                                    <ph.DataCtxReader>
                                      {$ctx => (
                                        <ProductCardJbs
                                          data-plasmic-name={"productCardJbs"}
                                          data-plasmic-override={
                                            overrides.productCardJbs
                                          }
                                          className={classNames(
                                            "__wab_instance",
                                            sty.productCardJbs
                                          )}
                                        />
                                      )}
                                    </ph.DataCtxReader>
                                  </ProductBox>
                                </div>
                              );
                            })}
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__sytZ
                              )}
                            >
                              <Button2
                                data-plasmic-name={"button2"}
                                data-plasmic-override={overrides.button2}
                                className={classNames(
                                  "__wab_instance",
                                  sty.button2
                                )}
                                color={"clear"}
                                endIcon={
                                  <Icon38Icon
                                    data-plasmic-name={"svg"}
                                    data-plasmic-override={overrides.svg}
                                    className={classNames(
                                      projectcss.all,
                                      sty.svg
                                    )}
                                    role={"img"}
                                  />
                                }
                                link={`/category/${"all"}`}
                                shape={"sharp"}
                                showEndIcon={true}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__vp07P
                                  )}
                                >
                                  {"See all"}
                                </div>
                              </Button2>
                            </div>
                          </div>
                        )}
                      </ph.DataCtxReader>
                    </GraphqlFetcher>
                  )}
                </ph.DataCtxReader>
              </ProductBox>
            </Section>
          </FullPage>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "fullPage",
    "columns",
    "pageMetadataOverride",
    "productMedia",
    "productPrice",
    "productVariantPicker",
    "addToCartCustomButton",
    "accordion",
    "section",
    "productCardJbs",
    "button2",
    "svg"
  ],

  fullPage: [
    "fullPage",
    "columns",
    "pageMetadataOverride",
    "productMedia",
    "productPrice",
    "productVariantPicker",
    "addToCartCustomButton",
    "accordion",
    "section",
    "productCardJbs",
    "button2",
    "svg"
  ],

  columns: [
    "columns",
    "pageMetadataOverride",
    "productMedia",
    "productPrice",
    "productVariantPicker",
    "addToCartCustomButton",
    "accordion"
  ],

  pageMetadataOverride: ["pageMetadataOverride"],
  productMedia: ["productMedia"],
  productPrice: ["productPrice"],
  productVariantPicker: ["productVariantPicker"],
  addToCartCustomButton: ["addToCartCustomButton"],
  accordion: ["accordion"],
  section: ["section", "productCardJbs", "button2", "svg"],
  productCardJbs: ["productCardJbs"],
  button2: ["button2", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  fullPage: typeof FullPage;
  columns: "div";
  pageMetadataOverride: typeof PlasmicHead;
  productMedia: typeof ProductMedia;
  productPrice: typeof ProductPriceComponent;
  productVariantPicker: typeof ProductVariantPicker;
  addToCartCustomButton: typeof AddToCartCustomButton;
  accordion: typeof AntdAccordion;
  section: typeof Section;
  productCardJbs: typeof ProductCardJbs;
  button2: typeof Button2;
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProductPage__OverridesType,
  DescendantsType<T>
>;

type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProductPage__VariantsArgs;
    args?: PlasmicProductPage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProductPage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicProductPage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProductPage__ArgProps,
          internalVariantPropNames: PlasmicProductPage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProductPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProductPage";
  } else {
    func.displayName = `PlasmicProductPage.${nodeName}`;
  }
  return func;
}

export const PlasmicProductPage = Object.assign(
  // Top-level PlasmicProductPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    fullPage: makeNodeComponent("fullPage"),
    columns: makeNodeComponent("columns"),
    pageMetadataOverride: makeNodeComponent("pageMetadataOverride"),
    productMedia: makeNodeComponent("productMedia"),
    productPrice: makeNodeComponent("productPrice"),
    productVariantPicker: makeNodeComponent("productVariantPicker"),
    addToCartCustomButton: makeNodeComponent("addToCartCustomButton"),
    accordion: makeNodeComponent("accordion"),
    section: makeNodeComponent("section"),
    productCardJbs: makeNodeComponent("productCardJbs"),
    button2: makeNodeComponent("button2"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicProductPage
    internalVariantProps: PlasmicProductPage__VariantProps,
    internalArgProps: PlasmicProductPage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicProductPage;
/* prettier-ignore-end */
