// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: heL2P6rJiLNgtnBJPb6i1m
// Component: dIysgpuSQtRE

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button2 from "../../Button2"; // plasmic-import: yEsI5slGwPm/component

import { useScreenVariants as useScreenVariants_6Hzia3M7Np4Ulu } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 6hzia3m7Np4ulu/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_jbs_storefront.module.css"; // plasmic-import: heL2P6rJiLNgtnBJPb6i1m/projectcss
import sty from "./PlasmicFullpagewidthSlide2.module.css"; // plasmic-import: dIysgpuSQtRE/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: ew07hyuAC0c/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: 3r4KXWygi9v/icon

createPlasmicElementProxy;

export type PlasmicFullpagewidthSlide2__VariantMembers = {};
export type PlasmicFullpagewidthSlide2__VariantsArgs = {};
type VariantPropType = keyof PlasmicFullpagewidthSlide2__VariantsArgs;
export const PlasmicFullpagewidthSlide2__VariantProps =
  new Array<VariantPropType>();

export type PlasmicFullpagewidthSlide2__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
};
type ArgPropType = keyof PlasmicFullpagewidthSlide2__ArgsType;
export const PlasmicFullpagewidthSlide2__ArgProps = new Array<ArgPropType>(
  "children",
  "slot",
  "slot2",
  "slot3"
);

export type PlasmicFullpagewidthSlide2__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultFullpagewidthSlide2Props {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  slot2?: React.ReactNode;
  slot3?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFullpagewidthSlide2__RenderFunc(props: {
  variants: PlasmicFullpagewidthSlide2__VariantsArgs;
  args: PlasmicFullpagewidthSlide2__ArgsType;
  overrides: PlasmicFullpagewidthSlide2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_6Hzia3M7Np4Ulu()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__mm5V3)}>
        {p.renderPlasmicSlot({
          defaultContents: (
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__fMSf)}
              displayHeight={"auto"}
              displayMaxHeight={"100%"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              src={{
                src: "/plasmic/jbs_storefront/images/image.svg",
                fullWidth: 150,
                fullHeight: 150,
                aspectRatio: 1
              }}
            />
          ),

          value: args.children
        })}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox___6Zvm9)}>
        <div className={classNames(projectcss.all, sty.freeBox___1WXf6)}>
          {p.renderPlasmicSlot({
            defaultContents: "Chakhna",
            value: args.slot,
            className: classNames(sty.slotTargetSlot)
          })}
        </div>
        <div className={classNames(projectcss.all, sty.freeBox___2DWCq)}>
          {p.renderPlasmicSlot({
            defaultContents:
              "Life is a party, these are the snacks our \ndelightful new Textile Collectibles ",
            value: args.slot2,
            className: classNames(sty.slotTargetSlot2)
          })}
        </div>
        {p.renderPlasmicSlot({
          defaultContents: (
            <Button2
              className={classNames("__wab_instance", sty.button2__pTyOk)}
              color={"red"}
            >
              {"Shop all Chakhna"}
            </Button2>
          ),
          value: args.slot3
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFullpagewidthSlide2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFullpagewidthSlide2__VariantsArgs;
    args?: PlasmicFullpagewidthSlide2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFullpagewidthSlide2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicFullpagewidthSlide2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicFullpagewidthSlide2__ArgProps,
          internalVariantPropNames: PlasmicFullpagewidthSlide2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFullpagewidthSlide2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFullpagewidthSlide2";
  } else {
    func.displayName = `PlasmicFullpagewidthSlide2.${nodeName}`;
  }
  return func;
}

export const PlasmicFullpagewidthSlide2 = Object.assign(
  // Top-level PlasmicFullpagewidthSlide2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicFullpagewidthSlide2
    internalVariantProps: PlasmicFullpagewidthSlide2__VariantProps,
    internalArgProps: PlasmicFullpagewidthSlide2__ArgProps
  }
);

export default PlasmicFullpagewidthSlide2;
/* prettier-ignore-end */
