// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: heL2P6rJiLNgtnBJPb6i1m
// Component: R6tZZ6EQ-gsb

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import FullPage from "../../FullPage"; // plasmic-import: VpRM2nIn0R/component
import Section from "../../Section"; // plasmic-import: GMAR4VOl00/component
import Slider from "react-slick"; // plasmic-import: HOQUyOpClJ/codeComponent
import Blackyellowborder from "../../Blackyellowborder"; // plasmic-import: qeyEUvMFwY/component

import { useScreenVariants as useScreenVariants_6Hzia3M7Np4Ulu } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 6hzia3m7Np4ulu/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_jbs_storefront.module.css"; // plasmic-import: heL2P6rJiLNgtnBJPb6i1m/projectcss
import sty from "./PlasmicAbout.module.css"; // plasmic-import: R6tZZ6EQ-gsb/css

createPlasmicElementProxy;

export type PlasmicAbout__VariantMembers = {};
export type PlasmicAbout__VariantsArgs = {};
type VariantPropType = keyof PlasmicAbout__VariantsArgs;
export const PlasmicAbout__VariantProps = new Array<VariantPropType>();

export type PlasmicAbout__ArgsType = {};
type ArgPropType = keyof PlasmicAbout__ArgsType;
export const PlasmicAbout__ArgProps = new Array<ArgPropType>();

export type PlasmicAbout__OverridesType = {
  root?: p.Flex<"div">;
  fullPage?: p.Flex<typeof FullPage>;
  h4?: p.Flex<"h4">;
  h1?: p.Flex<"h1">;
};

export interface DefaultAboutProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAbout__RenderFunc(props: {
  variants: PlasmicAbout__VariantsArgs;
  args: PlasmicAbout__ArgsType;
  overrides: PlasmicAbout__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_6Hzia3M7Np4Ulu()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <FullPage
            data-plasmic-name={"fullPage"}
            data-plasmic-override={overrides.fullPage}
            className={classNames("__wab_instance", sty.fullPage)}
          >
            <Section
              className={classNames("__wab_instance", sty.section__uUdAt)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___3OKZ)}>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__vprZ4)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/jbs_storefront/images/asset2Png.png",
                    fullWidth: 7607,
                    fullHeight: 3055,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5YmRm
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h4
                        data-plasmic-name={"h4"}
                        data-plasmic-override={overrides.h4}
                        className={classNames(
                          projectcss.all,
                          projectcss.h4,
                          projectcss.__wab_text,
                          sty.h4
                        )}
                      >
                        {
                          "We\u2019re Juhu Beach Studio and we work exclusively with textile waste.\nWe make beautiful, tasty products, do commissioned artworks and reaally fun workshops.\nCurious objects that make life more excitinggg"
                        }
                      </h4>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
            </Section>
            <Section
              className={classNames("__wab_instance", sty.section__zMq4Z)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__r0Jpl)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"100%"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/jbs_storefront/images/asset3Png.png",
                  fullWidth: 7170,
                  fullHeight: 3867,
                  aspectRatio: undefined
                }}
              />
            </Section>
            <Section
              className={classNames("__wab_instance", sty.section__ppS85)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__kYtE)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__py98A)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dyi4R
                    )}
                  >
                    {"How we started"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__exf8M
                    )}
                  >
                    {
                      "We met at college and shared the same khujli for collecting and making fascinating things, exploring markets, materials and anything that caught our eye."
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lrnzs
                    )}
                  >
                    {
                      "Over the next few years as we worked and learned more and more about the textile industry, we were so disillusioned by how irresponsible it was, that we found ourselves back in Mumbai wondering what to do :("
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__k7NwP
                    )}
                  >
                    {
                      "We set out to explore Mumbai the manufacturing hub for some answers and found LOTS and LOTS of textile waste instead. This was our chance to make the things we wanted, without making a bad problem even worse and so JBS was bornnn"
                    }
                  </div>
                </p.Stack>
                <div className={classNames(projectcss.all, sty.column__u114A)}>
                  <Slider
                    className={classNames(
                      "__wab_instance",
                      sty.sliderCarousel__lBx2Z
                    )}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__cKjVs)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__tx1Lb)}
                        displayHeight={"651px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/jbs_storefront/images/asset83Png.png",
                          fullWidth: 2612,
                          fullHeight: 3485,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__yqC2R)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__shPbV)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/jbs_storefront/images/asset84Png.png",
                          fullWidth: 2615,
                          fullHeight: 3487,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__iVLw)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___2J70B)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={{
                          src: "/plasmic/jbs_storefront/images/asset82Png.png",
                          fullWidth: 2612,
                          fullHeight: 3478,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </Slider>
                </div>
              </p.Stack>
            </Section>
            <Section
              className={classNames("__wab_instance", sty.section__j2Fxj)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__ihiLy)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__bZln9)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__na9KH)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lwlL7
                      )}
                    >
                      {"What's a Juhu Beach"}
                    </div>
                  </div>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__v3VCh)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rPcgt
                      )}
                    >
                      {
                        "It\u2019s the most wholesome place in Mumbai, and our favourite part of the city. People from all walks of life come here to chill, run with their dogs, practice a skill, everyone is so happy to escape from the craziness of real life for a little bit to just sit by the water, eat some bhel and daydream."
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ne5Pc
                      )}
                    >
                      {
                        "This is basically how we wanted this brand to feel too, just like at the beach, everyone is welcome, anything can happen, no cynicism, just vibes. While real life may be inescapable you can always make it more fun"
                      }
                    </div>
                  </p.Stack>
                </p.Stack>
              </div>
            </Section>
            <Section
              className={classNames("__wab_instance", sty.section__zxezt)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__bVCj)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wLmnM
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <h1
                        data-plasmic-name={"h1"}
                        data-plasmic-override={overrides.h1}
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1
                        )}
                      >
                        {"waste fellows "}
                      </h1>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__u8Xf)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/jbs_storefront/images/asset85Largepng.png",
                    fullWidth: 1658,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tr9LR
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontStyle: "italic", fontWeight: 700 }}
                    >
                      {"A"}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontStyle: "italic", fontWeight: 400 }}
                    >
                      {"dj."}
                    </span>
                    <React.Fragment>{"\n"}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700 }}
                    >
                      {"Term of endearment, derogatory"}
                    </span>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pjOvw
                  )}
                >
                  {
                    "Someone who takes timepass very seriously and may appear to be into random pointlessstuff (timepass) and may be dismissed as good for nothing, but the stuff they\u2019re into is actually quite fascinating and theyre super passionate about it and you love that about them. \n\u201cDude they\u2019re such waste fellows i love itt\u201d"
                  }
                </div>
              </p.Stack>
            </Section>
            <Section
              className={classNames("__wab_instance", sty.section__wMEy)}
            >
              <Blackyellowborder
                className={classNames(
                  "__wab_instance",
                  sty.blackyellowborder__u3P4U
                )}
              />

              <div className={classNames(projectcss.all, sty.freeBox__oOVd)}>
                <div
                  className={classNames(projectcss.all, sty.freeBox___30VTk)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9GxNi
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Team"}
                      </span>
                    </React.Fragment>
                  </div>
                </div>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__uym5W)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__adnja)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qcu10
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {
                            "We are so lucky to be able to train, employ and work with such an amazing team of women, our very own "
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"impossible mission task force"}
                        </span>
                        <React.Fragment>
                          {
                            ", each with their own special skill sets that can literally make anything when they work together."
                          }
                        </React.Fragment>
                      </React.Fragment>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__jIvsE)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6BHct
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {"We want to give lots and lots of women "}
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"opportunities to gain financial independence"}
                        </span>
                        <React.Fragment>
                          {
                            " or even just supplement their household income. We want our studio to be "
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {
                            "a safe, happy space, where they foster friendships and enjoy learning and making beautiful things"
                          }
                        </span>
                        <React.Fragment>{"."}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </div>
                </p.Stack>
                <div className={classNames(projectcss.all, sty.columns__rf6UN)}>
                  <div className={classNames(projectcss.all, sty.column__dIz1)}>
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__lsP7Y)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/jbs_storefront/images/asset10Png.png",
                        fullWidth: 3668,
                        fullHeight: 5886,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__rz8Li)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___0IuIu)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/jbs_storefront/images/asset11Png.png",
                        fullWidth: 3621,
                        fullHeight: 5672,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
              </div>
            </Section>
            <Section
              className={classNames("__wab_instance", sty.section__mbbOa)}
            >
              <Blackyellowborder
                className={classNames(
                  "__wab_instance",
                  sty.blackyellowborder__o9BDu
                )}
              />

              <div className={classNames(projectcss.all, sty.freeBox__xxwor)}>
                <div className={classNames(projectcss.all, sty.freeBox__de3Oj)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9VLxC
                    )}
                  >
                    {"Process"}
                  </div>
                </div>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__ta5Mn)}
                >
                  <div className={classNames(projectcss.all, sty.column__cLaR)}>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5DsUv
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {"We were very particular about the products "}
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"not looking like they\u2019re made of waste "}
                        </span>
                        <React.Fragment>
                          {
                            "so the process is quite painful now x but making these products is also our favourite thing about this business cuz when things work out its the best feeling ever, our nasha of choice X."
                          }
                        </React.Fragment>
                      </React.Fragment>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__kCdXm)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__e09Vi
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {
                            "90% of the process takes place in the studio and any waste that we generate in the process gets sorted and stored for use in other projects. "
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {
                            "Typically, you design something and then go get the materials, but for us it starts with finding materials first."
                          }
                        </span>
                      </React.Fragment>
                    </div>
                  </div>
                </p.Stack>
              </div>
            </Section>
            <Section
              className={classNames("__wab_instance", sty.section__ck63D)}
            >
              <Slider
                className={classNames(
                  "__wab_instance",
                  sty.sliderCarousel__cOddc
                )}
              >
                <div className={classNames(projectcss.all, sty.freeBox__neHuN)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___4GGb)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={
                      "https://static1.plasmic.app/components/react-slick/slide1.png"
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__ytN4)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__fpOPm)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={
                      "https://static1.plasmic.app/components/react-slick/slide2.png"
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__lcPjv)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__rMuuQ)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={
                      "https://static1.plasmic.app/components/react-slick/slide3.png"
                    }
                  />
                </div>
              </Slider>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jwKD
                )}
              >
                {"Sourcing"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ryWhh
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {"We go sourcing for our raw materials - "}
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"pre consumer waste"}
                  </span>
                  <React.Fragment>
                    {
                      " and get to see the craziest things - godowns filled floor to ceiling with thousands of meters of fabric in piles upto 30ft high, bags and bags of unused yarns, buttons, lace, etc. "
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {
                      "We test all our materials for colour fastness and material composition"
                    }
                  </span>
                  <React.Fragment>
                    {
                      " before we buy them and it has to happen quickly cuz you only find anything between 5-20 meters of one fabric at a time and you will "
                    }
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 700 }}
                  >
                    {"NEVER find the same material twice"}
                  </span>
                  <React.Fragment>
                    {" (thats why limited edition)."}
                  </React.Fragment>
                </React.Fragment>
              </div>
            </Section>
            <Section
              className={classNames("__wab_instance", sty.section__ch4Xy)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__rL0US)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ebm2Z
                  )}
                >
                  {"Our Materials"}
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__qg8Vf)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__kS5AX)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fA6Zf)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__g016Y)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__gYrm7
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rka1S
                          )}
                        >
                          {"Deadstock"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___677He
                          )}
                        >
                          {
                            "Dead stock is any unsold inventory that sits in storage for a long period of time. These goods are not expected to be sold in the near future. They were not ordered with the intention of storing them for a long time, as in the case of safety stock. This makes dead stock a drain on warehouse resources."
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__nPvVi)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__e7RmB)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__fSlu7)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__comFl
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__i7SxP
                          )}
                        >
                          {"Deadstock"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__juB9
                          )}
                        >
                          {
                            "Dead stock is any unsold inventory that sits in storage for a long period of time. These goods are not expected to be sold in the near future. They were not ordered with the intention of storing them for a long time, as in the case of safety stock. This makes dead stock a drain on warehouse resources."
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ejtac)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ci4L7)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__gqMUa)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bjwbd
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jpwAl
                          )}
                        >
                          {"Deadstock"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__mYp2K
                          )}
                        >
                          {
                            "Dead stock is any unsold inventory that sits in storage for a long period of time. These goods are not expected to be sold in the near future. They were not ordered with the intention of storing them for a long time, as in the case of safety stock. This makes dead stock a drain on warehouse resources."
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__rdBv)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__zxQfq)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__crHpA)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        loading={"lazy"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__kosC
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zgwNt
                          )}
                        >
                          {"Deadstock"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__z4ZJw
                          )}
                        >
                          {
                            "Dead stock is any unsold inventory that sits in storage for a long period of time. These goods are not expected to be sold in the near future. They were not ordered with the intention of storing them for a long time, as in the case of safety stock. This makes dead stock a drain on warehouse resources."
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </Section>
            <Section
              className={classNames("__wab_instance", sty.section__eHgi1)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__hy50G)}>
                <div className={classNames(projectcss.all, sty.freeBox__yk2S0)}>
                  <Slider
                    className={classNames(
                      "__wab_instance",
                      sty.sliderCarousel__jkvnj
                    )}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__g9Sra)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___1Je1H)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={{
                          src: "/plasmic/jbs_storefront/images/asset75Png2.png",
                          fullWidth: 4720,
                          fullHeight: 2655,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                  </Slider>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__sKvnY)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kCatH
                      )}
                    >
                      {"Designing & Sampling"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7C4F1
                      )}
                    >
                      {
                        "Once materials are aquired, we start by making lots of sketches of diff. versions of things based on how much/what fabric we have, what colors we have etc. This is quite challenging and we have to get really creative till something hits. Then we make lotss of samples (most of which are super bizarre) that we test and rework over and over again till all the details are perfect and everything hits."
                      }
                    </div>
                  </div>
                </div>
              </div>
            </Section>
            <Section
              className={classNames("__wab_instance", sty.section__swWzU)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___8IWHu)}>
                <div className={classNames(projectcss.all, sty.freeBox__twvWp)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hhmSt
                    )}
                  >
                    {"1125 mts of textile waste"}
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__dVDa)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__agHx6
                    )}
                  >
                    {"1500 products"}
                  </div>
                </div>
              </div>
            </Section>
            <Section
              className={classNames("__wab_instance", sty.section__ve8Ea)}
            >
              <div className={classNames(projectcss.all, sty.freeBox___299Qi)}>
                <div className={classNames(projectcss.all, sty.freeBox__hGgMn)}>
                  <Slider
                    className={classNames(
                      "__wab_instance",
                      sty.sliderCarousel__n0Ger
                    )}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__knjVe)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__jsrOk)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        src={
                          "https://static1.plasmic.app/components/react-slick/slide1.png"
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__gzts)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__cEka3)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={
                          "https://static1.plasmic.app/components/react-slick/slide2.png"
                        }
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__yrBnK)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__gIFnk)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"auto"}
                        src={
                          "https://static1.plasmic.app/components/react-slick/slide3.png"
                        }
                      />
                    </div>
                  </Slider>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__eARsP)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yGmvK
                      )}
                    >
                      {"Production"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__aAif
                      )}
                    >
                      {
                        "After making a perfect final sample, all our fabrics are washed and then we then train our girlz to make the things. While that happens, we desperately try to optimize the number of patterns that can be cut from a piece of fabric, plan everyones schedules, make detailed specification sheets, quality check everything, make hundreds of calls and lists till all our sketches turn into finished productssss."
                      }
                    </div>
                  </div>
                </div>
              </div>
            </Section>
            <Section
              className={classNames("__wab_instance", sty.section__tneL3)}
            >
              <Blackyellowborder
                className={classNames(
                  "__wab_instance",
                  sty.blackyellowborder__vsb6A
                )}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wxvGl
                )}
              >
                {"Agenda"}
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__rsaqC)}>
                <div className={classNames(projectcss.all, sty.freeBox__vFjwm)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__vCli7)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___30NE
                    )}
                  >
                    {
                      "To explore pre-and post consumer textile waste as a viable raw material for a scalable enterprise. Basically build a kachre ka empire"
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__m6NRl)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__bgq7B)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ulhZ0
                    )}
                  >
                    {
                      "Make beautiful, magical, high concept, high quality products that we\u2019ve always dreamed of making and having"
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__qg19I)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__kAbar)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hOqXh
                    )}
                  >
                    {
                      "Create a community of other creative wastefellows who share our love for beautiful sustainable products and an unshitty future for ALL"
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__hluNl)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__tNcCq)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6DcfN
                    )}
                  >
                    {
                      "Create lots and lots of jobs and build a highly skilled team of women who can make anything and everything"
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox___6Of)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__nujIn)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8CNtD
                    )}
                  >
                    {
                      "Get funding and start a giant pink factory with a recycling plant that runs on green energy"
                    }
                  </div>
                </div>
              </div>
            </Section>
          </FullPage>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "fullPage", "h4", "h1"],
  fullPage: ["fullPage", "h4", "h1"],
  h4: ["h4"],
  h1: ["h1"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  fullPage: typeof FullPage;
  h4: "h4";
  h1: "h1";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAbout__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAbout__VariantsArgs;
    args?: PlasmicAbout__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAbout__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicAbout__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicAbout__ArgProps,
          internalVariantPropNames: PlasmicAbout__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAbout__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAbout";
  } else {
    func.displayName = `PlasmicAbout.${nodeName}`;
  }
  return func;
}

export const PlasmicAbout = Object.assign(
  // Top-level PlasmicAbout renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    fullPage: makeNodeComponent("fullPage"),
    h4: makeNodeComponent("h4"),
    h1: makeNodeComponent("h1"),

    // Metadata about props expected for PlasmicAbout
    internalVariantProps: PlasmicAbout__VariantProps,
    internalArgProps: PlasmicAbout__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAbout;
/* prettier-ignore-end */
