// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: heL2P6rJiLNgtnBJPb6i1m

import * as React from "react";
import { getActiveVariation } from "@plasmicapp/react-web/lib/splits";
import { ScheduleContext } from "./PlasmicGlobalVariant__Schedule"; // plasmic-import: zd5JVdnkSq7D/globalVariant

export interface PlasmicSplitsProviderProps {
  children?: React.ReactNode;
  traits?: Record<string, string>;
}

const splits = [
  {
    id: "ShaqSCBmIkM9",
    projectId: "heL2P6rJiLNgtnBJPb6i1m",
    externalId: null,
    type: "segment",
    slices: [
      { id: "FdcbBB87JzKp", externalId: null, cond: {}, contents: [] },
      {
        id: "AxH7vLkCgpTD",
        externalId: null,
        cond: {
          "<=": [
            "2023-12-14T01:33:43.504Z",
            { var: "time" },
            "2023-12-14T01:40:20.430Z"
          ]
        },
        contents: [
          {
            type: "global-variant",
            projectId: "heL2P6rJiLNgtnBJPb6i1m",
            groupId: "zd5JVdnkSq7D",
            group: "Schedule",
            variant: "override"
          }
        ]
      }
    ]
  }
];

function getGlobalContextValueFromVariation(
  groupId: string,
  variation: Record<string, string>
) {
  let groupValue: string | undefined = undefined;
  Object.keys(variation).forEach((variationKey: string) => {
    const [_type, splitId] = variationKey.split(".");
    const sliceId = variation[variationKey];
    const split = splits.find(
      s => s.id === splitId || s.externalId === splitId
    );
    if (split) {
      const slice = split.slices.find(
        s => s.id === sliceId || s.externalId === sliceId
      );
      if (slice) {
        const content = slice.contents.find(c => c.groupId === groupId);
        if (content) {
          groupValue = content.variant;
        }
      }
    }
  });
  return groupValue;
}

export default function PlasmicSplitsProvider(
  props: PlasmicSplitsProviderProps
) {
  const { children, traits } = props;
  const variation = getActiveVariation({
    splits,
    traits: traits ?? {}
  });

  return (
    <>
      <ScheduleContext.Provider
        value={getGlobalContextValueFromVariation("zd5JVdnkSq7D", variation)}
      >
        {children}
      </ScheduleContext.Provider>
    </>
  );
}
