// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: heL2P6rJiLNgtnBJPb6i1m
// Component: NFEkw9xPSE

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button2 from "../../Button2"; // plasmic-import: yEsI5slGwPm/component
import { CategoryCollection } from "@plasmicpkgs/commerce"; // plasmic-import: ny07p45F84c_/codeComponent
import { CategoryField } from "@plasmicpkgs/commerce"; // plasmic-import: hzqiq--xdG5T/codeComponent

import { useScreenVariants as useScreenVariants_6Hzia3M7Np4Ulu } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 6hzia3m7Np4ulu/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_jbs_storefront.module.css"; // plasmic-import: heL2P6rJiLNgtnBJPb6i1m/projectcss
import sty from "./PlasmicJbsMenu.module.css"; // plasmic-import: NFEkw9xPSE/css

import HamburgersvgIcon from "./icons/PlasmicIcon__Hamburgersvg"; // plasmic-import: QybYSQyE3W/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: ew07hyuAC0c/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: 3r4KXWygi9v/icon

createPlasmicElementProxy;

export type PlasmicJbsMenu__VariantMembers = {
  revealMenu: "revealMenu";
  revealSubMenu: "revealSubMenu";
};
export type PlasmicJbsMenu__VariantsArgs = {
  revealMenu?: SingleBooleanChoiceArg<"revealMenu">;
  revealSubMenu?: SingleBooleanChoiceArg<"revealSubMenu">;
};
type VariantPropType = keyof PlasmicJbsMenu__VariantsArgs;
export const PlasmicJbsMenu__VariantProps = new Array<VariantPropType>(
  "revealMenu",
  "revealSubMenu"
);

export type PlasmicJbsMenu__ArgsType = {};
type ArgPropType = keyof PlasmicJbsMenu__ArgsType;
export const PlasmicJbsMenu__ArgProps = new Array<ArgPropType>();

export type PlasmicJbsMenu__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
  freeBox?: p.Flex<"div">;
  categoryCollection?: p.Flex<typeof CategoryCollection>;
  categoryField?: p.Flex<typeof CategoryField>;
};

export interface DefaultJbsMenuProps {
  revealMenu?: SingleBooleanChoiceArg<"revealMenu">;
  revealSubMenu?: SingleBooleanChoiceArg<"revealSubMenu">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicJbsMenu__RenderFunc(props: {
  variants: PlasmicJbsMenu__VariantsArgs;
  args: PlasmicJbsMenu__ArgsType;
  overrides: PlasmicJbsMenu__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof p.useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "revealMenu",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.revealMenu
      },
      {
        path: "revealSubMenu",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.revealSubMenu
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_6Hzia3M7Np4Ulu()
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootrevealMenu]: hasVariant($state, "revealMenu", "revealMenu"),
          [sty.rootrevealSubMenu]: hasVariant(
            $state,
            "revealSubMenu",
            "revealSubMenu"
          )
        }
      )}
    >
      <Button2
        className={classNames("__wab_instance", sty.button2__df7Kl, {
          [sty.button2revealMenu__df7KlxT6MH]: hasVariant(
            $state,
            "revealMenu",
            "revealMenu"
          ),
          [sty.button2revealSubMenu__df7KlBjo1Y]: hasVariant(
            $state,
            "revealSubMenu",
            "revealSubMenu"
          )
        })}
        color={"red"}
        onClick={async event => {
          const $steps = {};

          $steps["updateRevealMenu"] = true
            ? (() => {
                const actionArgs = {
                  vgroup: "revealMenu",
                  operation: 2,
                  value: "revealMenu"
                };
                return (({ vgroup, value }) => {
                  if (typeof value === "string") {
                    value = [value];
                  }

                  const oldValue = p.get($state, vgroup);
                  p.set($state, vgroup, !oldValue);
                  return !oldValue;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateRevealMenu"] != null &&
            typeof $steps["updateRevealMenu"] === "object" &&
            typeof $steps["updateRevealMenu"].then === "function"
          ) {
            $steps["updateRevealMenu"] = await $steps["updateRevealMenu"];
          }
        }}
        size={"compact"}
      >
        <HamburgersvgIcon
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          className={classNames(projectcss.all, sty.svg, {
            [sty.svgrevealMenu]: hasVariant($state, "revealMenu", "revealMenu"),
            [sty.svgrevealSubMenu]: hasVariant(
              $state,
              "revealSubMenu",
              "revealSubMenu"
            )
          })}
          role={"img"}
        />
      </Button2>
      <Button2
        className={classNames("__wab_instance", sty.button2__zu9X, {
          [sty.button2revealMenu__zu9XxT6MH]: hasVariant(
            $state,
            "revealMenu",
            "revealMenu"
          ),
          [sty.button2revealSubMenu__zu9XBjo1Y]: hasVariant(
            $state,
            "revealSubMenu",
            "revealSubMenu"
          )
        })}
        color={hasVariant($state, "revealMenu", "revealMenu") ? "red" : "red"}
        link={`/`}
        size={"compact"}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__oPaqX,
            {
              [sty.textrevealMenu__oPaqXxT6MH]: hasVariant(
                $state,
                "revealMenu",
                "revealMenu"
              ),
              [sty.textrevealSubMenu__oPaqXBjo1Y]: hasVariant(
                $state,
                "revealSubMenu",
                "revealSubMenu"
              )
            }
          )}
        >
          {"Home"}
        </div>
      </Button2>
      <Button2
        className={classNames("__wab_instance", sty.button2__v8Y8, {
          [sty.button2revealMenu__v8Y8XT6MH]: hasVariant(
            $state,
            "revealMenu",
            "revealMenu"
          ),
          [sty.button2revealSubMenu__v8Y8Bjo1Y]: hasVariant(
            $state,
            "revealSubMenu",
            "revealSubMenu"
          )
        })}
        color={hasVariant($state, "revealMenu", "revealMenu") ? "red" : "red"}
        link={`/about`}
        size={"compact"}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__llyAo,
            {
              [sty.textrevealMenu__llyAOxT6MH]: hasVariant(
                $state,
                "revealMenu",
                "revealMenu"
              ),
              [sty.textrevealSubMenu__llyAoBjo1Y]: hasVariant(
                $state,
                "revealSubMenu",
                "revealSubMenu"
              )
            }
          )}
        >
          {"About"}
        </div>
      </Button2>
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox, {
          [sty.freeBoxrevealMenu]: hasVariant(
            $state,
            "revealMenu",
            "revealMenu"
          ),
          [sty.freeBoxrevealSubMenu]: hasVariant(
            $state,
            "revealSubMenu",
            "revealSubMenu"
          )
        })}
      >
        <Button2
          className={classNames("__wab_instance", sty.button2__lZ0WF, {
            [sty.button2revealMenu__lZ0WFxT6MH]: hasVariant(
              $state,
              "revealMenu",
              "revealMenu"
            ),
            [sty.button2revealSubMenu__lZ0WFBjo1Y]: hasVariant(
              $state,
              "revealSubMenu",
              "revealSubMenu"
            )
          })}
          color={hasVariant($state, "revealMenu", "revealMenu") ? "red" : "red"}
          onClick={async event => {
            const $steps = {};

            $steps["updateRevealSubMenu"] = true
              ? (() => {
                  const actionArgs = { vgroup: "revealSubMenu", operation: 2 };
                  return (({ vgroup, value }) => {
                    if (typeof value === "string") {
                      value = [value];
                    }

                    const oldValue = p.get($state, vgroup);
                    p.set($state, vgroup, !oldValue);
                    return !oldValue;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateRevealSubMenu"] != null &&
              typeof $steps["updateRevealSubMenu"] === "object" &&
              typeof $steps["updateRevealSubMenu"].then === "function"
            ) {
              $steps["updateRevealSubMenu"] = await $steps[
                "updateRevealSubMenu"
              ];
            }
          }}
          size={"compact"}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__vmlsA,
              {
                [sty.textrevealMenu__vmlsAxT6MH]: hasVariant(
                  $state,
                  "revealMenu",
                  "revealMenu"
                ),
                [sty.textrevealSubMenu__vmlsABjo1Y]: hasVariant(
                  $state,
                  "revealSubMenu",
                  "revealSubMenu"
                )
              }
            )}
          >
            {"Shop"}
          </div>
        </Button2>
        <CategoryCollection
          data-plasmic-name={"categoryCollection"}
          data-plasmic-override={overrides.categoryCollection}
          className={classNames("__wab_instance", sty.categoryCollection, {
            [sty.categoryCollectionrevealMenu]: hasVariant(
              $state,
              "revealMenu",
              "revealMenu"
            ),
            [sty.categoryCollectionrevealSubMenu]: hasVariant(
              $state,
              "revealSubMenu",
              "revealSubMenu"
            )
          })}
          emptyMessage={
            <ph.DataCtxReader>
              {$ctx => (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__coRT,
                    {
                      [sty.textrevealMenu__coRTxT6MH]: hasVariant(
                        $state,
                        "revealMenu",
                        "revealMenu"
                      )
                    }
                  )}
                >
                  {"No collection found!"}
                </div>
              )}
            </ph.DataCtxReader>
          }
          loadingMessage={
            <ph.DataCtxReader>
              {$ctx => (
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bxrNg,
                    {
                      [sty.textrevealMenu__bxrNGxT6MH]: hasVariant(
                        $state,
                        "revealMenu",
                        "revealMenu"
                      )
                    }
                  )}
                >
                  {"Loading..."}
                </div>
              )}
            </ph.DataCtxReader>
          }
        >
          <ph.DataCtxReader>
            {$ctx => (
              <Button2
                alignment={"leftAligned"}
                className={classNames("__wab_instance", sty.button2__j93E8, {
                  [sty.button2revealMenu__j93E8XT6MH]: hasVariant(
                    $state,
                    "revealMenu",
                    "revealMenu"
                  )
                })}
                color={"red"}
                link={`/category/${(() => {
                  try {
                    return $ctx.currentCategory.slug;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}`}
                size={"compact"}
              >
                <CategoryField
                  data-plasmic-name={"categoryField"}
                  data-plasmic-override={overrides.categoryField}
                  className={classNames("__wab_instance", sty.categoryField)}
                  field={"name"}
                />
              </Button2>
            )}
          </ph.DataCtxReader>
        </CategoryCollection>
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg", "freeBox", "categoryCollection", "categoryField"],
  svg: ["svg"],
  freeBox: ["freeBox", "categoryCollection", "categoryField"],
  categoryCollection: ["categoryCollection", "categoryField"],
  categoryField: ["categoryField"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
  freeBox: "div";
  categoryCollection: typeof CategoryCollection;
  categoryField: typeof CategoryField;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicJbsMenu__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicJbsMenu__VariantsArgs;
    args?: PlasmicJbsMenu__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicJbsMenu__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicJbsMenu__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicJbsMenu__ArgProps,
          internalVariantPropNames: PlasmicJbsMenu__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicJbsMenu__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicJbsMenu";
  } else {
    func.displayName = `PlasmicJbsMenu.${nodeName}`;
  }
  return func;
}

export const PlasmicJbsMenu = Object.assign(
  // Top-level PlasmicJbsMenu renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    freeBox: makeNodeComponent("freeBox"),
    categoryCollection: makeNodeComponent("categoryCollection"),
    categoryField: makeNodeComponent("categoryField"),

    // Metadata about props expected for PlasmicJbsMenu
    internalVariantProps: PlasmicJbsMenu__VariantProps,
    internalArgProps: PlasmicJbsMenu__ArgProps
  }
);

export default PlasmicJbsMenu;
/* prettier-ignore-end */
