/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: heL2P6rJiLNgtnBJPb6i1m
// Component: Tu3iaahTzpLP

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_jbs_storefront.module.css"; // plasmic-import: heL2P6rJiLNgtnBJPb6i1m/projectcss
import sty from "./PlasmicCountdownNumber2.module.css"; // plasmic-import: Tu3iaahTzpLP/css

createPlasmicElementProxy;

export type PlasmicCountdownNumber2__VariantMembers = {};
export type PlasmicCountdownNumber2__VariantsArgs = {};
type VariantPropType = keyof PlasmicCountdownNumber2__VariantsArgs;
export const PlasmicCountdownNumber2__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCountdownNumber2__ArgsType = {
  number?: React.ReactNode;
  unit?: React.ReactNode;
};
type ArgPropType = keyof PlasmicCountdownNumber2__ArgsType;
export const PlasmicCountdownNumber2__ArgProps = new Array<ArgPropType>(
  "number",
  "unit"
);

export type PlasmicCountdownNumber2__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultCountdownNumber2Props {
  number?: React.ReactNode;
  unit?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCountdownNumber2__RenderFunc(props: {
  variants: PlasmicCountdownNumber2__VariantsArgs;
  args: PlasmicCountdownNumber2__ArgsType;
  overrides: PlasmicCountdownNumber2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__bd0Fs)}>
        {renderPlasmicSlot({
          defaultContents: "42",
          value: args.number,
          className: classNames(sty.slotTargetNumber)
        })}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox___6VoAr)}>
        {renderPlasmicSlot({
          defaultContents: "Days",
          value: args.unit
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCountdownNumber2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCountdownNumber2__VariantsArgs;
    args?: PlasmicCountdownNumber2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCountdownNumber2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCountdownNumber2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCountdownNumber2__ArgProps,
          internalVariantPropNames: PlasmicCountdownNumber2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCountdownNumber2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCountdownNumber2";
  } else {
    func.displayName = `PlasmicCountdownNumber2.${nodeName}`;
  }
  return func;
}

export const PlasmicCountdownNumber2 = Object.assign(
  // Top-level PlasmicCountdownNumber2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicCountdownNumber2
    internalVariantProps: PlasmicCountdownNumber2__VariantProps,
    internalArgProps: PlasmicCountdownNumber2__ArgProps
  }
);

export default PlasmicCountdownNumber2;
/* prettier-ignore-end */
